ak_vpc_cidr = "10.0.0.0/16"
ak_vpc_name = "ak-infra-vpc"
ak_public_sub_cidr_block = [ "10.0.1.0/24", "10.0.2.0/24" ]
ak_cidr_private_subnet = [ "10.0.3.0/24", "10.0.4.0/24" ]
ak_availability_zone = [ "us-east-1a", "us-east-1b" ]
ak_ami_id = "ami-06dd92ecc74fdfb36e"
ak_domain_name = "example.com"
ak_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCg5fUtFvRcnlTapH5EUP1zqvDbRcTqnzqjAS9L2PT5YJ55MMFtBqniQVOgbUHMHYULZtQCATFfvLaxsOnivEBuImo2hJ0LaiVcHyN6QcyTyyNgqSqVH9p7tKxiQ5q3sCvTmA89oc1G1z11XxRXXpRda1JceopwFqMppDUhGmSEmZbYJNd5We8O+vct3uYeAOw42DLR5TMU9YgjJMVYnRDptloiYRwjOn8iREpmo8P00rUxmlUVKXiuYNP6RuBDt5IVI0RUZLPWLKtu76AKYLsdvAxl8AxHtOG3klFW5j3496TqzDw5lUBPRdQlEQMx1WWk0bP+MglNOr6RjqObVplRyMH4/W42WxFEh2xAk1urObAggv4Wg0N+giJbbgtYi4UIaVOevTyHGvvYqvYDNsO+eXoYex/gK3RnffrqR1+mRIrsOw8IlPLJJ2lmeeZiVTJK6TfypHWxd1jpVN19D2vb/6FSZlyRxuqaChJxrqj3u5OpKNH5d6asjqg6zY93UqKFNfD9u4Xp0FM2SaAjIYPJ61FqabknZXj+i4f7/62kd3AgbRmjjjUGf5slEDjiDOE2yU4A7wbKM5Flkvl4NloD1O6G3HXlEE+3WDFljjUYHKvcCjNWSRg7jWzyVUoc4Jq5HjXKiX9q4an1AYm+DhohMmuX0W3V9Tac8pE5ytE+CQ== kemedjiokenlefakanicet@penguin"
ak_env = "Development"
ak_instance_type = "t2.micro"
ak_tag_name = "Ubuntu Linux EC2"
ak_enable_public_ip_address = true
ak_lb_target_group_name = "ak-infra-target-group"
ak_lb_target_group_port = 5000
ak_lb_target_group_protocol = "HTTP"
ak_lb_name = "ak-infra-alb"
ak_is_external = false
ak_lb_type = "application"
ak_lb_tag_name = "ak-infra-alb"
ak_lb_listner_port = 5000
ak_lb_listner_protocol = "HTTP"
ak_lb_listner_default_action = "forward"
ak_lb_https_listner_port = 443
ak_lb_https_listner_protocol = "HTTPS"
ak_lb_target_group_attachment_port = 5000
ak_allocate_storage = 10
ak_db_engine = "mysql"
ak_db_instance_class = "db.t2.micro"
ak_storage_type = "gp2"
ak_engine_version = "5.7"
ak_db_subnet_group_name = "ak-infra-rds-subnet-group"
ak_mysql_db_identifier = "mydb"
ak_mysql_username = "anicet"
ak_mysql_password = "sadjdgsgfgas"
ak_mysql_dbname = "devdevopsdb"
ak_ec2_sg_name = "SG for EC2 to enable SSH(22) and HTTP(80)"
ak_ec2_sg_name_python_api = "SG EC2 for enabling port 5000"
ak_rds_mysql_sg_name = "ak-infra-rds-subnet-group"
ak_aws_lb_dns_name = "ak-infra-alb"